### ISSUE TITLE
State Change

### ISSUE THREAD

**Issue by Thet-Tun-Aung** [4ndroidev/DownloadManager#1]
How to change state when file doesn't exit in storage? In order to re-download again.

issue has been solved by following code:

DownloadManager  manager = DownloadManager.getInstance();
                        List<DownloadInfo> infos = manager.getAllInfo();
                        for (DownloadInfo info : infos) {
                            if (info.key.equals(task.key)) {
                                manager.delete(info);
                                break;
                            }
                        }

                        downloadAdapter.notifyItemChanged(position);

thanks @4ndroidev

**Comment by 4ndroidev** [comment]
@Thet-Tun-Aung, Thank you for reporting this issue, can you give more information ?
I have fixed some issues including some state issues recently , and deployed it as a library on JCenter. Others, can you update the project and  check if the issue still exists? Thanks!

**Comment by Thet-Tun-Aung** [comment]
issue has been solved by following code:

DownloadManager manager = DownloadManager.getInstance();
List infos = manager.getAllInfo();
for (DownloadInfo info : infos) {
if (info.key.equals(task.key)) {
manager.delete(info);
break;
}
}

downloadAdapter.notifyItemChanged(position);

thanks @4ndroidev
